version: '3'
services:
  # Node.js App
  web:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongo
    env_file: .env
    command: ["npm", "start"]

  # NoSQL datastore (MongoDB)
  mongo:
    image: mongo
    ports:
      - 27017:27017
